### ISSUE TITLE
DefaultNotification Pause/Cancel buttons don`t work

### ISSUE THREAD

**Issue by BordoBereli** [tonyofrancis/Fetch#327]

**Comment by BordoBereli** [comment]
My configuration is like this: FetchConfiguration.Builder(context)
            .enableFileExistChecks(true)
            .enableHashCheck(true)
            .enableLogging(BuildConfig.DEBUG)
            .enableRetryOnNetworkGain(true)
            .setDownloadConcurrentLimit(1)
            .setGlobalNetworkType(NetworkType.ALL)
            .setHttpDownloader(OkHttpDownloader(OkHttpClient().newBuilder().build()))
            .setNamespace("Bulut_Göz_Name_Space")
            .setNotificationManager(DefaultFetchNotificationManager(context))
            .enableAutoStart(false)
            .build()

**Comment by BordoBereli** [comment]
I did fix it by changing "val intent = Intent(ACTION_NOTIFICATION_ACTION)" to
            "val intent = Intent(context, FetchNotificationBroadcastReceiver::class.java).apply {
                action = ACTION_NOTIFICATION_ACTION
            }"
on DefaultFetchNotificationManager -> fun getActionPendingIntent(...)

**Comment by tonyofrancis** [comment]
@BordoBereli  looking into this. Will post back soon.

**Comment by tonyofrancis** [comment]
@BordoBereli Fixed in the next release. Will report back once released.

**Comment by tonyofrancis** [comment]
@BordoBereli  Fetch version 3.0.0 has been released with this fix.

**Comment by xeinebiu** [comment]
Still does not work.
Clicking Pause or Cancel will stop the download

**Comment by jahirfiquitiva** [comment]
This doesn't seem to be fixed yet. I'm using version `3.1.4` @tonyofrancis

**Comment by ghost** [comment]
still doesn't work
