### ISSUE TITLE
don't resume download if content-type or content-length changed

### ISSUE THREAD

**Issue by badrazizi** [tonyofrancis/Fetch#536]
if download session expired it's suppose to fail but instead it over write the file with the new response.

i propose that it check if content-type or content-length or both are changed before it try to resume download.

**Comment by tonyofrancis** [comment]
@badrazizi Thanks for using Fetch.

Depending on your `FetchConfiguration` settings or the retry setting on the request
```java
//example
  request.setAutoRetryMaxAttempts(5);
  request.setEnqueueAction(EnqueueAction.UPDATE_ACCORDINGLY);
``` 
Fetch will attempt to re-download the file. Setting these settings to **NOT** retry should solve this issue. 

When Fetch retries a failed download it will do its best to start where it left off. If it cannot verify the data integrity the download will continue from the beginning.

**Comment by badrazizi** [comment]
It's did not solve it, If the server return response code 404 yes fetch fail and i can update request link to working one.
But if server return response code 200 while resource not found fetch actually overwrite the file with new response which is usually "text/html", Here it should check content-type or content-length or both before continue from the beginning to avoid overwrite file with different content

**Comment by tonyofrancis** [comment]
I see what you are saying. Let me look into this further. Will report back.
